# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.elf_model import ELFModel

class TestELFModel(unittest.TestCase):
    """ELFModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ELFModel:
        """Test ELFModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ELFModel`
        """
        model = ELFModel()
        if include_optional:
            return ELFModel(
                architecture = '',
                build_id = '',
                debug_info = {
                    'key' : null
                    },
                dynamic_entries = [
                    revengai.models.elf_dynamic_entry.ElfDynamicEntry(
                        tag = '', 
                        value = 56, )
                    ],
                dynamic_symbols = [
                    revengai.models.elf_symbol.ELFSymbol(
                        binding = '', 
                        name = '', 
                        section_index = 56, 
                        size = 56, 
                        type = '', 
                        value = 56, 
                        visibility = '', )
                    ],
                endianness = '',
                entry_point = 56,
                entry_point_bytes = '',
                export_hash = '',
                exported_functions = [
                    ''
                    ],
                file_type = '',
                import_hash = '',
                imports = revengai.models.elf_import_model.ELFImportModel(
                    imports = [
                        ''
                        ], 
                    number_of_imports = 56, ),
                notes = [
                    {
                        'key' : null
                        }
                    ],
                relocations = [
                    revengai.models.elf_relocation.ELFRelocation(
                        addend = 56, 
                        address = 56, 
                        is_dynamic = True, 
                        is_pltgot = True, 
                        size = 56, 
                        symbol_name = '', 
                        type = '', )
                    ],
                sections = [
                    revengai.models.elf_section.ELFSection(
                        alignment = 56, 
                        entropy = 1.337, 
                        file_offset = 56, 
                        flags = '', 
                        flags_raw = 56, 
                        name = '', 
                        raw_size = 56, 
                        type = '', 
                        virtual_address = 56, 
                        virtual_size = 56, )
                    ],
                security = revengai.models.elf_security.ELFSecurity(
                    canary = True, 
                    nx = True, 
                    pie = True, 
                    relo = True, 
                    stripped = True, ),
                segments = [
                    revengai.models.elf_segment.ELFSegment(
                        alignment = 56, 
                        file_offset = 56, 
                        flags = '', 
                        flags_raw = 56, 
                        physical_address = 56, 
                        physical_size = 56, 
                        type = '', 
                        virtual_address = 56, 
                        virtual_size = 56, )
                    ],
                symbols = [
                    revengai.models.elf_symbol.ELFSymbol(
                        binding = '', 
                        name = '', 
                        section_index = 56, 
                        size = 56, 
                        type = '', 
                        value = 56, 
                        visibility = '', )
                    ],
                version_info = {
                    'key' : null
                    }
            )
        else:
            return ELFModel(
                architecture = '',
                build_id = '',
                debug_info = {
                    'key' : null
                    },
                dynamic_entries = [
                    revengai.models.elf_dynamic_entry.ElfDynamicEntry(
                        tag = '', 
                        value = 56, )
                    ],
                dynamic_symbols = [
                    revengai.models.elf_symbol.ELFSymbol(
                        binding = '', 
                        name = '', 
                        section_index = 56, 
                        size = 56, 
                        type = '', 
                        value = 56, 
                        visibility = '', )
                    ],
                endianness = '',
                entry_point = 56,
                entry_point_bytes = '',
                export_hash = '',
                exported_functions = [
                    ''
                    ],
                file_type = '',
                import_hash = '',
                imports = revengai.models.elf_import_model.ELFImportModel(
                    imports = [
                        ''
                        ], 
                    number_of_imports = 56, ),
                notes = [
                    {
                        'key' : null
                        }
                    ],
                relocations = [
                    revengai.models.elf_relocation.ELFRelocation(
                        addend = 56, 
                        address = 56, 
                        is_dynamic = True, 
                        is_pltgot = True, 
                        size = 56, 
                        symbol_name = '', 
                        type = '', )
                    ],
                sections = [
                    revengai.models.elf_section.ELFSection(
                        alignment = 56, 
                        entropy = 1.337, 
                        file_offset = 56, 
                        flags = '', 
                        flags_raw = 56, 
                        name = '', 
                        raw_size = 56, 
                        type = '', 
                        virtual_address = 56, 
                        virtual_size = 56, )
                    ],
                security = revengai.models.elf_security.ELFSecurity(
                    canary = True, 
                    nx = True, 
                    pie = True, 
                    relo = True, 
                    stripped = True, ),
                segments = [
                    revengai.models.elf_segment.ELFSegment(
                        alignment = 56, 
                        file_offset = 56, 
                        flags = '', 
                        flags_raw = 56, 
                        physical_address = 56, 
                        physical_size = 56, 
                        type = '', 
                        virtual_address = 56, 
                        virtual_size = 56, )
                    ],
                symbols = [
                    revengai.models.elf_symbol.ELFSymbol(
                        binding = '', 
                        name = '', 
                        section_index = 56, 
                        size = 56, 
                        type = '', 
                        value = 56, 
                        visibility = '', )
                    ],
                version_info = {
                    'key' : null
                    },
        )
        """

    def testELFModel(self):
        """Test ELFModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
