# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.api.firmware_api import FirmwareApi


class TestFirmwareApi(unittest.TestCase):
    """FirmwareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FirmwareApi()

    def tearDown(self) -> None:
        pass

    def test_get_binaries_for_firmware_task(self) -> None:
        """Test case for get_binaries_for_firmware_task

        Upload firmware for unpacking
        """
        pass

    def test_upload_firmware(self) -> None:
        """Test case for upload_firmware

        Upload firmware for unpacking
        """
        pass


if __name__ == '__main__':
    unittest.main()
