# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.stream_events200_response_inner import StreamEvents200ResponseInner

class TestStreamEvents200ResponseInner(unittest.TestCase):
    """StreamEvents200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamEvents200ResponseInner:
        """Test StreamEvents200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamEvents200ResponseInner`
        """
        model = StreamEvents200ResponseInner()
        if include_optional:
            return StreamEvents200ResponseInner(
                data = { },
                event = 'TOOL_CONFIRMATION_REQUIRED',
                id = 56,
                retry = 56
            )
        else:
            return StreamEvents200ResponseInner(
                data = { },
                event = 'TOOL_CONFIRMATION_REQUIRED',
        )
        """

    def testStreamEvents200ResponseInner(self):
        """Test StreamEvents200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
