# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.xref_from_response import XrefFromResponse

class TestXrefFromResponse(unittest.TestCase):
    """XrefFromResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> XrefFromResponse:
        """Test XrefFromResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `XrefFromResponse`
        """
        model = XrefFromResponse()
        if include_optional:
            return XrefFromResponse(
                is_call = True,
                is_data = True,
                is_scalar = True,
                is_string = True,
                orig_str_encoding = '',
                raw_data = '',
                segment = revengai.models.segment_info.SegmentInfo(
                    end = 56, 
                    name = '', 
                    r = True, 
                    start = 56, 
                    w = True, 
                    x = True, ),
                value = '',
                xref_to = ''
            )
        else:
            return XrefFromResponse(
                value = '',
                xref_to = '',
        )
        """

    def testXrefFromResponse(self):
        """Test XrefFromResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
