# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is Similarity Search Engine for executable binaries

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.update_function_data_types import UpdateFunctionDataTypes

class TestUpdateFunctionDataTypes(unittest.TestCase):
    """UpdateFunctionDataTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateFunctionDataTypes:
        """Test UpdateFunctionDataTypes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateFunctionDataTypes`
        """
        model = UpdateFunctionDataTypes()
        if include_optional:
            return UpdateFunctionDataTypes(
                data_types_version = 56,
                data_types = revengai.models.function_info.FunctionInfo(
                    func_types = null, 
                    func_deps = [
                        null
                        ], )
            )
        else:
            return UpdateFunctionDataTypes(
                data_types_version = 56,
                data_types = revengai.models.function_info.FunctionInfo(
                    func_types = null, 
                    func_deps = [
                        null
                        ], ),
        )
        """

    def testUpdateFunctionDataTypes(self):
        """Test UpdateFunctionDataTypes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
