# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is Similarity Search Engine for executable binaries

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.binary_additional_details_data_response import BinaryAdditionalDetailsDataResponse

class TestBinaryAdditionalDetailsDataResponse(unittest.TestCase):
    """BinaryAdditionalDetailsDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BinaryAdditionalDetailsDataResponse:
        """Test BinaryAdditionalDetailsDataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BinaryAdditionalDetailsDataResponse`
        """
        model = BinaryAdditionalDetailsDataResponse()
        if include_optional:
            return BinaryAdditionalDetailsDataResponse(
                file = revengai.models.file_metadata.FileMetadata(
                    size = 56, 
                    friendly_size = '', 
                    entropy = 1.337, 
                    hashes = revengai.models.file_hashes.FileHashes(
                        md5 = '', 
                        sha1 = '', 
                        sha256 = '', 
                        sha512 = '', 
                        sha3_224 = '', 
                        sha3_256 = '', 
                        sha3_384 = '', 
                        sha3_512 = '', ), ),
                pe = revengai.models.pe_model.PEModel(
                    type = '', 
                    timestamps = null, 
                    architecture = '', 
                    checksum = 56, 
                    image_base = 56, 
                    security = null, 
                    version_info = {
                        'key' : null
                        }, 
                    debug_info = null, 
                    number_of_resources = 56, 
                    entry_point = null, 
                    signature = null, 
                    dotnet = True, 
                    debug_stripped = True, 
                    import_hash = '', 
                    export_hash = '', 
                    rich_header_hash = '', 
                    sections = null, 
                    imports = null, 
                    exports = null, 
                    icon_data = null, ),
                elf = revengai.models.elf_model.ELFModel(
                    file_type = '', 
                    architecture = '', 
                    endianness = '', 
                    entry_point = 56, 
                    entry_point_bytes = '', 
                    import_hash = '', 
                    export_hash = '', 
                    build_id = '', 
                    security = revengai.models.elf_security.ELFSecurity(
                        pie = True, 
                        stripped = True, 
                        canary = True, 
                        nx = True, 
                        relo = True, ), 
                    sections = [
                        revengai.models.elf_section.ELFSection(
                            name = '', 
                            type = '', 
                            virtual_address = 56, 
                            virtual_size = 56, 
                            raw_size = 56, 
                            file_offset = 56, 
                            flags = '', 
                            flags_raw = 56, 
                            entropy = 1.337, 
                            alignment = 56, )
                        ], 
                    segments = [
                        revengai.models.elf_segment.ELFSegment(
                            type = '', 
                            virtual_address = 56, 
                            virtual_size = 56, 
                            physical_address = 56, 
                            physical_size = 56, 
                            file_offset = 56, 
                            flags = '', 
                            flags_raw = 56, 
                            alignment = 56, )
                        ], 
                    symbols = [
                        revengai.models.elf_symbol.ELFSymbol(
                            name = '', 
                            value = 56, 
                            size = 56, 
                            type = '', 
                            binding = '', 
                            visibility = '', 
                            section_index = 56, )
                        ], 
                    dynamic_symbols = [
                        revengai.models.elf_symbol.ELFSymbol(
                            name = '', 
                            value = 56, 
                            size = 56, 
                            type = '', 
                            binding = '', 
                            visibility = '', 
                            section_index = 56, )
                        ], 
                    relocations = [
                        revengai.models.elf_relocation.ELFRelocation(
                            address = 56, 
                            type = '', 
                            size = 56, 
                            addend = 56, 
                            symbol_name = '', 
                            is_dynamic = True, 
                            is_pltgot = True, )
                        ], 
                    imports = revengai.models.elf_import_model.ELFImportModel(
                        number_of_imports = 56, 
                        imports = [
                            ''
                            ], ), 
                    exported_functions = [
                        ''
                        ], 
                    dynamic_entries = [
                        revengai.models.elf_dynamic_entry.ElfDynamicEntry(
                            tag = '', 
                            value = 56, )
                        ], 
                    notes = [
                        {
                            'key' : null
                            }
                        ], 
                    debug_info = {
                        'key' : null
                        }, 
                    version_info = {
                        'key' : null
                        }, )
            )
        else:
            return BinaryAdditionalDetailsDataResponse(
                file = revengai.models.file_metadata.FileMetadata(
                    size = 56, 
                    friendly_size = '', 
                    entropy = 1.337, 
                    hashes = revengai.models.file_hashes.FileHashes(
                        md5 = '', 
                        sha1 = '', 
                        sha256 = '', 
                        sha512 = '', 
                        sha3_224 = '', 
                        sha3_256 = '', 
                        sha3_384 = '', 
                        sha3_512 = '', ), ),
        )
        """

    def testBinaryAdditionalDetailsDataResponse(self):
        """Test BinaryAdditionalDetailsDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
