# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.collection_response_binaries_inner import CollectionResponseBinariesInner

class TestCollectionResponseBinariesInner(unittest.TestCase):
    """CollectionResponseBinariesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionResponseBinariesInner:
        """Test CollectionResponseBinariesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionResponseBinariesInner`
        """
        model = CollectionResponseBinariesInner()
        if include_optional:
            return CollectionResponseBinariesInner(
                analysis_id = 56,
                binary_id = 56,
                binary_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_system_analysis = True,
                owner_id = 56,
                sha_256_hash = ''
            )
        else:
            return CollectionResponseBinariesInner(
                analysis_id = 56,
                binary_id = 56,
                binary_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_system_analysis = True,
                owner_id = 56,
                sha_256_hash = '',
        )
        """

    def testCollectionResponseBinariesInner(self):
        """Test CollectionResponseBinariesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
