# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.base_response_list_user_activity_response import BaseResponseListUserActivityResponse

class TestBaseResponseListUserActivityResponse(unittest.TestCase):
    """BaseResponseListUserActivityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResponseListUserActivityResponse:
        """Test BaseResponseListUserActivityResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseResponseListUserActivityResponse`
        """
        model = BaseResponseListUserActivityResponse()
        if include_optional:
            return BaseResponseListUserActivityResponse(
                data = [
                    revengai.models.user_activity_response.UserActivityResponse(
                        actions = '', 
                        activity_scope = '', 
                        creation = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        message = '', 
                        sources = '', 
                        username = '', )
                    ],
                errors = [
                    revengai.models.error_model.ErrorModel(
                        code = '', 
                        message = '', )
                    ],
                message = '',
                meta = revengai.models.meta_model.MetaModel(
                    pagination = revengai.models.pagination_model.PaginationModel(
                        has_next_page = True, 
                        page_number = 56, 
                        page_size = 56, ), ),
                status = True
            )
        else:
            return BaseResponseListUserActivityResponse(
        )
        """

    def testBaseResponseListUserActivityResponse(self):
        """Test BaseResponseListUserActivityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
