# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.sse_event_tool_confirmation_required_data import SseEventToolConfirmationRequiredData

class TestSseEventToolConfirmationRequiredData(unittest.TestCase):
    """SseEventToolConfirmationRequiredData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SseEventToolConfirmationRequiredData:
        """Test SseEventToolConfirmationRequiredData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SseEventToolConfirmationRequiredData`
        """
        model = SseEventToolConfirmationRequiredData()
        if include_optional:
            return SseEventToolConfirmationRequiredData(
                data = None,
                event_id = 56,
                type = ''
            )
        else:
            return SseEventToolConfirmationRequiredData(
                data = None,
                event_id = 56,
                type = '',
        )
        """

    def testSseEventToolConfirmationRequiredData(self):
        """Test SseEventToolConfirmationRequiredData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
