# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.function_list_item import FunctionListItem

class TestFunctionListItem(unittest.TestCase):
    """FunctionListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionListItem:
        """Test FunctionListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionListItem`
        """
        model = FunctionListItem()
        if include_optional:
            return FunctionListItem(
                debug = True,
                id = 56,
                mangled_name = '',
                name = '',
                name_source = revengai.models.name_source_type.NameSourceType(
                    analysis_id = 56, 
                    binary_id = 56, 
                    function_id = 56, 
                    type = 'SYSTEM', ),
                name_source_type = 'SYSTEM',
                size = 56,
                vaddr = 56
            )
        else:
            return FunctionListItem(
                debug = True,
                id = 56,
                mangled_name = '',
                name = '',
                name_source = revengai.models.name_source_type.NameSourceType(
                    analysis_id = 56, 
                    binary_id = 56, 
                    function_id = 56, 
                    type = 'SYSTEM', ),
                name_source_type = 'SYSTEM',
                size = 56,
                vaddr = 56,
        )
        """

    def testFunctionListItem(self):
        """Test FunctionListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
