# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.ai_decompilation_task_status import AiDecompilationTaskStatus

class TestAiDecompilationTaskStatus(unittest.TestCase):
    """AiDecompilationTaskStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAiDecompilationTaskStatus(self):
        """Test AiDecompilationTaskStatus"""
        # inst = AiDecompilationTaskStatus()

if __name__ == '__main__':
    unittest.main()
