# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.base_response_triage_report_response import BaseResponseTriageReportResponse

class TestBaseResponseTriageReportResponse(unittest.TestCase):
    """BaseResponseTriageReportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResponseTriageReportResponse:
        """Test BaseResponseTriageReportResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseResponseTriageReportResponse`
        """
        model = BaseResponseTriageReportResponse()
        if include_optional:
            return BaseResponseTriageReportResponse(
                status = True,
                data = revengai.models.triage_report_response.TriageReportResponse(
                    software_score = 0, 
                    summary = '', 
                    functions = [
                        revengai.models.triage_function_response.TriageFunctionResponse(
                            id = 56, 
                            address = 56, 
                            summary = '', 
                            score = 0, 
                            capabilities = [
                                'packing_and_obfuscation'
                                ], )
                        ], ),
                message = '',
                errors = [
                    revengai.models.error_model.ErrorModel(
                        code = '', 
                        message = '', )
                    ],
                meta = revengai.models.meta_model.MetaModel(
                    pagination = revengai.models.pagination_model.PaginationModel(
                        page_size = 56, 
                        page_number = 56, 
                        has_next_page = True, ), )
            )
        else:
            return BaseResponseTriageReportResponse(
        )
        """

    def testBaseResponseTriageReportResponse(self):
        """Test BaseResponseTriageReportResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
