# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.xref_response import XrefResponse

class TestXrefResponse(unittest.TestCase):
    """XrefResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> XrefResponse:
        """Test XrefResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `XrefResponse`
        """
        model = XrefResponse()
        if include_optional:
            return XrefResponse(
                xref_to_list = [
                    revengai.models.xref_to_response.XrefToResponse(
                        value = '', 
                        is_scalar = True, 
                        is_call = True, 
                        is_data = True, 
                        is_string = True, 
                        raw_data = '', 
                        segment = revengai.models.segment_info.SegmentInfo(
                            name = '', 
                            r = True, 
                            w = True, 
                            x = True, 
                            start = 56, 
                            end = 56, ), 
                        orig_str_encoding = '', 
                        xref_from = '', )
                    ],
                xref_from_list = [
                    revengai.models.xref_from_response.XrefFromResponse(
                        value = '', 
                        is_scalar = True, 
                        is_call = True, 
                        is_data = True, 
                        is_string = True, 
                        raw_data = '', 
                        segment = revengai.models.segment_info.SegmentInfo(
                            name = '', 
                            r = True, 
                            w = True, 
                            x = True, 
                            start = 56, 
                            end = 56, ), 
                        orig_str_encoding = '', 
                        xref_to = '', )
                    ]
            )
        else:
            return XrefResponse(
                xref_to_list = [
                    revengai.models.xref_to_response.XrefToResponse(
                        value = '', 
                        is_scalar = True, 
                        is_call = True, 
                        is_data = True, 
                        is_string = True, 
                        raw_data = '', 
                        segment = revengai.models.segment_info.SegmentInfo(
                            name = '', 
                            r = True, 
                            w = True, 
                            x = True, 
                            start = 56, 
                            end = 56, ), 
                        orig_str_encoding = '', 
                        xref_from = '', )
                    ],
                xref_from_list = [
                    revengai.models.xref_from_response.XrefFromResponse(
                        value = '', 
                        is_scalar = True, 
                        is_call = True, 
                        is_data = True, 
                        is_string = True, 
                        raw_data = '', 
                        segment = revengai.models.segment_info.SegmentInfo(
                            name = '', 
                            r = True, 
                            w = True, 
                            x = True, 
                            start = 56, 
                            end = 56, ), 
                        orig_str_encoding = '', 
                        xref_to = '', )
                    ],
        )
        """

    def testXrefResponse(self):
        """Test XrefResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
