# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.base_response_analysis_bulk_add_tags_response import BaseResponseAnalysisBulkAddTagsResponse

class TestBaseResponseAnalysisBulkAddTagsResponse(unittest.TestCase):
    """BaseResponseAnalysisBulkAddTagsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResponseAnalysisBulkAddTagsResponse:
        """Test BaseResponseAnalysisBulkAddTagsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseResponseAnalysisBulkAddTagsResponse`
        """
        model = BaseResponseAnalysisBulkAddTagsResponse()
        if include_optional:
            return BaseResponseAnalysisBulkAddTagsResponse(
                status = True,
                data = revengai.models.analysis_bulk_add_tags_response.AnalysisBulkAddTagsResponse(
                    results = [
                        revengai.models.analysis_bulk_add_tags_response_item.AnalysisBulkAddTagsResponseItem(
                            analysis_id = 56, 
                            message = '', 
                            error = '', )
                        ], ),
                message = '',
                errors = [
                    revengai.models.error_model.ErrorModel(
                        code = '', 
                        message = '', )
                    ],
                meta = revengai.models.meta_model.MetaModel(
                    pagination = revengai.models.pagination_model.PaginationModel(
                        page_size = 56, 
                        page_number = 56, 
                        has_next_page = True, ), )
            )
        else:
            return BaseResponseAnalysisBulkAddTagsResponse(
        )
        """

    def testBaseResponseAnalysisBulkAddTagsResponse(self):
        """Test BaseResponseAnalysisBulkAddTagsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
