# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.models.base_response_xref_response import BaseResponseXrefResponse

class TestBaseResponseXrefResponse(unittest.TestCase):
    """BaseResponseXrefResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResponseXrefResponse:
        """Test BaseResponseXrefResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseResponseXrefResponse`
        """
        model = BaseResponseXrefResponse()
        if include_optional:
            return BaseResponseXrefResponse(
                data = revengai.models.xref_response.XrefResponse(
                    xref_from_list = [
                        revengai.models.xref_from_response.XrefFromResponse(
                            is_call = True, 
                            is_data = True, 
                            is_scalar = True, 
                            is_string = True, 
                            orig_str_encoding = '', 
                            raw_data = '', 
                            segment = revengai.models.segment_info.SegmentInfo(
                                end = 56, 
                                name = '', 
                                r = True, 
                                start = 56, 
                                w = True, 
                                x = True, ), 
                            value = '', 
                            xref_to = '', )
                        ], 
                    xref_to_list = [
                        revengai.models.xref_to_response.XrefToResponse(
                            is_call = True, 
                            is_data = True, 
                            is_scalar = True, 
                            is_string = True, 
                            orig_str_encoding = '', 
                            raw_data = '', 
                            value = '', 
                            xref_from = '', )
                        ], ),
                errors = [
                    revengai.models.error_model.ErrorModel(
                        code = '', 
                        message = '', )
                    ],
                message = '',
                meta = revengai.models.meta_model.MetaModel(
                    pagination = revengai.models.pagination_model.PaginationModel(
                        has_next_page = True, 
                        page_number = 56, 
                        page_size = 56, ), ),
                status = True
            )
        else:
            return BaseResponseXrefResponse(
        )
        """

    def testBaseResponseXrefResponse(self):
        """Test BaseResponseXrefResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
