# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from revengai.api.agent_api import AgentApi


class TestAgentApi(unittest.TestCase):
    """AgentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentApi()

    def tearDown(self) -> None:
        pass

    def test_check_capabilities_task_status_v2_analyses_analysis_id_agent_capabilities_status_get(self) -> None:
        """Test case for check_capabilities_task_status_v2_analyses_analysis_id_agent_capabilities_status_get

        Check the status of a capabilities analysis workflow
        """
        pass

    def test_check_report_analysis_task_status_v2_analyses_analysis_id_agent_report_analysis_status_get(self) -> None:
        """Test case for check_report_analysis_task_status_v2_analyses_analysis_id_agent_report_analysis_status_get

        Check the status of a report analysis workflow
        """
        pass

    def test_check_triage_task_status_v2_analyses_analysis_id_agent_triage_status_get(self) -> None:
        """Test case for check_triage_task_status_v2_analyses_analysis_id_agent_triage_status_get

        Check the status of a triage analysis workflow
        """
        pass

    def test_create_capabilities_task_v2_analyses_analysis_id_agent_capabilities_post(self) -> None:
        """Test case for create_capabilities_task_v2_analyses_analysis_id_agent_capabilities_post

        Queues a capabilities analysis workflow process
        """
        pass

    def test_create_report_analysis_task_v2_analyses_analysis_id_agent_report_analysis_post(self) -> None:
        """Test case for create_report_analysis_task_v2_analyses_analysis_id_agent_report_analysis_post

        Queues a combined report analysis workflow process
        """
        pass

    def test_create_triage_task_v2_analyses_analysis_id_agent_triage_post(self) -> None:
        """Test case for create_triage_task_v2_analyses_analysis_id_agent_triage_post

        Queues a triage analysis workflow process
        """
        pass

    def test_get_capabilities_result_v2_analyses_analysis_id_agent_capabilities_get(self) -> None:
        """Test case for get_capabilities_result_v2_analyses_analysis_id_agent_capabilities_get

        Get Capabilities Result
        """
        pass

    def test_get_report_analysis_result_v2_analyses_analysis_id_agent_report_analysis_get(self) -> None:
        """Test case for get_report_analysis_result_v2_analyses_analysis_id_agent_report_analysis_get

        Get Report Analysis Result
        """
        pass

    def test_get_triage_result_v2_analyses_analysis_id_agent_triage_get(self) -> None:
        """Test case for get_triage_result_v2_analyses_analysis_id_agent_triage_get

        Get Triage Result
        """
        pass


if __name__ == '__main__':
    unittest.main()
