# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppApiRestV2CollectionsEnumsOrderBy(str, Enum):
    """
    AppApiRestV2CollectionsEnumsOrderBy
    """

    """
    allowed enum values
    """
    CREATED = 'created'
    COLLECTION = 'collection'
    MODEL = 'model'
    OWNER = 'owner'
    COLLECTION_SIZE = 'collection_size'
    UPDATED = 'updated'
    UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppApiRestV2CollectionsEnumsOrderBy from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        """Fall back to the unknown default for values not defined in the SDK."""
        return cls.__members__.get("UNKNOWN_DEFAULT_OPEN_API")


