# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Artifact(BaseModel):
    """
    Artifact
    """ # noqa: E501
    direction: Optional[StrictStr] = None
    dump_addr: Optional[StrictStr] = None
    dump_pid: Optional[StrictInt] = None
    file_type: Optional[StrictStr] = None
    host: Optional[StrictStr] = None
    is_pe: StrictBool
    mime_type: Optional[StrictStr] = None
    name: Optional[StrictStr]
    network_source: Optional[StrictStr] = None
    original_filename: Optional[StrictStr] = None
    path: Optional[StrictStr]
    process_seqid: Optional[StrictInt] = None
    reason: StrictStr
    response_status: Optional[StrictInt] = None
    sha256: Optional[StrictStr] = None
    size: StrictInt
    source: Optional[StrictStr]
    uri: Optional[StrictStr] = None
    was_mapped: Optional[StrictBool] = None
    yara_hits: Optional[List[StrictStr]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["direction", "dump_addr", "dump_pid", "file_type", "host", "is_pe", "mime_type", "name", "network_source", "original_filename", "path", "process_seqid", "reason", "response_status", "sha256", "size", "source", "uri", "was_mapped", "yara_hits"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['written_by_target_process', 'binary_detected', 'shellcode_detected', 'file_type_detected', 'yara_match', 'network_request', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('written_by_target_process', 'binary_detected', 'shellcode_detected', 'file_type_detected', 'yara_match', 'network_request', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Artifact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if direction (nullable) is None
        # and model_fields_set contains the field
        if self.direction is None and "direction" in self.model_fields_set:
            _dict['direction'] = None

        # set to None if dump_addr (nullable) is None
        # and model_fields_set contains the field
        if self.dump_addr is None and "dump_addr" in self.model_fields_set:
            _dict['dump_addr'] = None

        # set to None if file_type (nullable) is None
        # and model_fields_set contains the field
        if self.file_type is None and "file_type" in self.model_fields_set:
            _dict['file_type'] = None

        # set to None if host (nullable) is None
        # and model_fields_set contains the field
        if self.host is None and "host" in self.model_fields_set:
            _dict['host'] = None

        # set to None if mime_type (nullable) is None
        # and model_fields_set contains the field
        if self.mime_type is None and "mime_type" in self.model_fields_set:
            _dict['mime_type'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if network_source (nullable) is None
        # and model_fields_set contains the field
        if self.network_source is None and "network_source" in self.model_fields_set:
            _dict['network_source'] = None

        # set to None if original_filename (nullable) is None
        # and model_fields_set contains the field
        if self.original_filename is None and "original_filename" in self.model_fields_set:
            _dict['original_filename'] = None

        # set to None if path (nullable) is None
        # and model_fields_set contains the field
        if self.path is None and "path" in self.model_fields_set:
            _dict['path'] = None

        # set to None if sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.sha256 is None and "sha256" in self.model_fields_set:
            _dict['sha256'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if uri (nullable) is None
        # and model_fields_set contains the field
        if self.uri is None and "uri" in self.model_fields_set:
            _dict['uri'] = None

        # set to None if yara_hits (nullable) is None
        # and model_fields_set contains the field
        if self.yara_hits is None and "yara_hits" in self.model_fields_set:
            _dict['yara_hits'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Artifact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "direction": obj.get("direction"),
            "dump_addr": obj.get("dump_addr"),
            "dump_pid": obj.get("dump_pid"),
            "file_type": obj.get("file_type"),
            "host": obj.get("host"),
            "is_pe": obj.get("is_pe"),
            "mime_type": obj.get("mime_type"),
            "name": obj.get("name"),
            "network_source": obj.get("network_source"),
            "original_filename": obj.get("original_filename"),
            "path": obj.get("path"),
            "process_seqid": obj.get("process_seqid"),
            "reason": obj.get("reason"),
            "response_status": obj.get("response_status"),
            "sha256": obj.get("sha256"),
            "size": obj.get("size"),
            "source": obj.get("source"),
            "uri": obj.get("uri"),
            "was_mapped": obj.get("was_mapped"),
            "yara_hits": obj.get("yara_hits")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


