# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateUserInputBody(BaseModel):
    """
    CreateUserInputBody
    """ # noqa: E501
    credits: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Initial credit balance in credits (1 credit = 1000 units); defaults to 10 credits")
    email: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Email address")
    first_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="First name")
    last_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Last name")
    password: Annotated[str, Field(min_length=8, strict=True, max_length=128)] = Field(description="Initial password")
    role: Optional[StrictStr] = Field(default=None, description="User role (defaults to USER)")
    tier: Optional[StrictStr] = Field(default=None, description="User tier (defaults to ENTHUSIAST)")
    time_zone: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="IANA time zone")
    username: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Username")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["credits", "email", "first_name", "last_name", "password", "role", "tier", "time_zone", "username"]

    @field_validator('email')
    def email_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^@\s]+@[^@\s]+\.[^@\s]+$/")
        return value

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['USER', 'ADMIN', 'SUPERADMIN', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('USER', 'ADMIN', 'SUPERADMIN', 'unknown_default_open_api')")
        return value

    @field_validator('tier')
    def tier_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ENTHUSIAST', 'REVERSER', 'BUG_HUNTER', 'MALWARE_ANALYST', 'SECURITY_RESEARCHER', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('ENTHUSIAST', 'REVERSER', 'BUG_HUNTER', 'MALWARE_ANALYST', 'SECURITY_RESEARCHER', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateUserInputBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateUserInputBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "credits": obj.get("credits"),
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "password": obj.get("password"),
            "role": obj.get("role"),
            "tier": obj.get("tier"),
            "time_zone": obj.get("time_zone"),
            "username": obj.get("username")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


