# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Filters(str, Enum):
    """
    Filters
    """

    """
    allowed enum values
    """
    OFFICIAL_ONLY = 'official_only'
    USER_ONLY = 'user_only'
    TEAM_ONLY = 'team_only'
    PUBLIC_ONLY = 'public_only'
    HIDE_EMPTY = 'hide_empty'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Filters from a JSON string"""
        return cls(json.loads(json_str))


