# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from revengai.models.call_edge import CallEdge
from typing import Optional, Set
from typing_extensions import Self

class FunctionCallEdges(BaseModel):
    """
    FunctionCallEdges
    """ # noqa: E501
    callees: Optional[List[CallEdge]]
    callers: Optional[List[CallEdge]]
    function_id: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["callees", "callers", "function_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FunctionCallEdges from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in callees (list)
        _items = []
        if self.callees:
            for _item_callees in self.callees:
                if _item_callees:
                    _items.append(_item_callees.to_dict())
            _dict['callees'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in callers (list)
        _items = []
        if self.callers:
            for _item_callers in self.callers:
                if _item_callers:
                    _items.append(_item_callers.to_dict())
            _dict['callers'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if callees (nullable) is None
        # and model_fields_set contains the field
        if self.callees is None and "callees" in self.model_fields_set:
            _dict['callees'] = None

        # set to None if callers (nullable) is None
        # and model_fields_set contains the field
        if self.callers is None and "callers" in self.model_fields_set:
            _dict['callers'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FunctionCallEdges from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "callees": [CallEdge.from_dict(_item) for _item in obj["callees"]] if obj.get("callees") is not None else None,
            "callers": [CallEdge.from_dict(_item) for _item in obj["callers"]] if obj.get("callers") is not None else None,
            "function_id": obj.get("function_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


