# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class MatchedFunction(BaseModel):
    """
    MatchedFunction
    """ # noqa: E501
    analysis_id: StrictInt = Field(description="Analysis the candidate's binary belongs to")
    binary_id: StrictInt = Field(description="Binary the candidate belongs to")
    binary_name: StrictStr = Field(description="Binary name")
    confidence: Union[StrictFloat, StrictInt] = Field(description="Softmax-normalised confidence over the candidate pool")
    debug: StrictBool = Field(description="Whether the candidate's name came from debug info")
    function_id: StrictInt = Field(description="Candidate function ID")
    function_name: StrictStr = Field(description="Candidate function name")
    function_vaddr: StrictInt = Field(description="Candidate's virtual address inside its binary")
    mangled_name: StrictStr = Field(description="Mangled name when available")
    sha_256_hash: StrictStr = Field(description="SHA-256 of the candidate's binary")
    similarity: Union[StrictFloat, StrictInt] = Field(description="Cosine similarity scaled to a percentage")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["analysis_id", "binary_id", "binary_name", "confidence", "debug", "function_id", "function_name", "function_vaddr", "mangled_name", "sha_256_hash", "similarity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchedFunction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchedFunction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analysis_id": obj.get("analysis_id"),
            "binary_id": obj.get("binary_id"),
            "binary_name": obj.get("binary_name"),
            "confidence": obj.get("confidence"),
            "debug": obj.get("debug"),
            "function_id": obj.get("function_id"),
            "function_name": obj.get("function_name"),
            "function_vaddr": obj.get("function_vaddr"),
            "mangled_name": obj.get("mangled_name"),
            "sha_256_hash": obj.get("sha_256_hash"),
            "similarity": obj.get("similarity")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


