# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from revengai.models.ioc import IOC
from revengai.models.mitre_technique import MITRETechnique
from typing import Optional, Set
from typing_extensions import Self

class ReportAnalysisResponse(BaseModel):
    """
    ReportAnalysisResponse
    """ # noqa: E501
    summary: StrictStr = Field(description="A markdown summary of the report")
    software_type: StrictStr = Field(description="The type of software being analyzed")
    total_number_of_functions: StrictInt = Field(description="The total number of functions identified in the binary")
    number_of_analysed_functions: StrictInt = Field(description="The number of functions that were analyzed in the binary")
    attack_flow_summary: StrictStr = Field(description="A summary in markdown format of the attack flow")
    iocs: List[IOC] = Field(description="A list of IOCs (Indicators of Compromise) found in the analysis", alias="IOCs")
    executable_techniques: List[MITRETechnique] = Field(description="A series of MITRE Techniques found")
    yara_rule: StrictStr = Field(description="The YARA rule generated for the binary")
    __properties: ClassVar[List[str]] = ["summary", "software_type", "total_number_of_functions", "number_of_analysed_functions", "attack_flow_summary", "IOCs", "executable_techniques", "yara_rule"]

    @field_validator('software_type')
    def software_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Malicious', 'Benign', 'Potentially Unwanted Application (PUA)', 'Legitimate', 'Backdoored Legitimate Software']):
            raise ValueError("must be one of enum values ('Malicious', 'Benign', 'Potentially Unwanted Application (PUA)', 'Legitimate', 'Backdoored Legitimate Software')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportAnalysisResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in iocs (list)
        _items = []
        if self.iocs:
            for _item_iocs in self.iocs:
                if _item_iocs:
                    _items.append(_item_iocs.to_dict())
            _dict['IOCs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in executable_techniques (list)
        _items = []
        if self.executable_techniques:
            for _item_executable_techniques in self.executable_techniques:
                if _item_executable_techniques:
                    _items.append(_item_executable_techniques.to_dict())
            _dict['executable_techniques'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportAnalysisResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "summary": obj.get("summary"),
            "software_type": obj.get("software_type"),
            "total_number_of_functions": obj.get("total_number_of_functions"),
            "number_of_analysed_functions": obj.get("number_of_analysed_functions"),
            "attack_flow_summary": obj.get("attack_flow_summary"),
            "IOCs": [IOC.from_dict(_item) for _item in obj["IOCs"]] if obj.get("IOCs") is not None else None,
            "executable_techniques": [MITRETechnique.from_dict(_item) for _item in obj["executable_techniques"]] if obj.get("executable_techniques") is not None else None,
            "yara_rule": obj.get("yara_rule")
        })
        return _obj


