# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from revengai.models.api_call import ApiCall
from typing import Optional, Set
from typing_extensions import Self

class ReportEvent(BaseModel):
    """
    ReportEvent
    """ # noqa: E501
    api_calls: Optional[List[ApiCall]] = None
    process_seqid: Optional[StrictInt] = None
    total_bytes_requested: Optional[StrictInt] = None
    type: Optional[StrictStr]
    value: Optional[StrictStr] = None
    value_name: Optional[StrictStr] = None
    write_count: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["api_calls", "process_seqid", "total_bytes_requested", "type", "value", "value_name", "write_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in api_calls (list)
        _items = []
        if self.api_calls:
            for _item_api_calls in self.api_calls:
                if _item_api_calls:
                    _items.append(_item_api_calls.to_dict())
            _dict['api_calls'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if api_calls (nullable) is None
        # and model_fields_set contains the field
        if self.api_calls is None and "api_calls" in self.model_fields_set:
            _dict['api_calls'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if value_name (nullable) is None
        # and model_fields_set contains the field
        if self.value_name is None and "value_name" in self.model_fields_set:
            _dict['value_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_calls": [ApiCall.from_dict(_item) for _item in obj["api_calls"]] if obj.get("api_calls") is not None else None,
            "process_seqid": obj.get("process_seqid"),
            "total_bytes_requested": obj.get("total_bytes_requested"),
            "type": obj.get("type"),
            "value": obj.get("value"),
            "value_name": obj.get("value_name"),
            "write_count": obj.get("write_count")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


