# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SuggestedMemberView(BaseModel):
    """
    SuggestedMemberView
    """ # noqa: E501
    bit_offset: Optional[StrictInt] = Field(description="Bit offset within the containing word for a bitfield member.")
    byte_offset: Optional[StrictInt] = Field(description="Offset within the type. Null when no placement could be established.")
    byte_size: Optional[StrictInt] = Field(description="Width of the access in bytes.")
    confidence: Optional[StrictStr] = Field(description="Where suggested_type came from. declared and inferred were observed; width knows only the access width; model is the language model's proposal.")
    name: StrictStr = Field(description="Name the member renders as: a database or frozen name where one exists, else the suggested one.")
    origin: StrictStr = Field(description="Which function revealed this member: self, caller:<function_id> or callee:<function_id>.")
    packed: StrictBool = Field(description="The member sits at an offset its own width does not divide.")
    placement: StrictStr = Field(description="observed means the offset was read off an access; guessed means the model proposed it; unplaced means the member has no offset.")
    suggested_type: Optional[StrictStr] = Field(description="Type expression for the member.")
    token: Optional[StrictStr] = Field(default=None, description="Placeholder this member renders as in the tokenised source. Absent for a member no access in this function revealed.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["bit_offset", "byte_offset", "byte_size", "confidence", "name", "origin", "packed", "placement", "suggested_type", "token"]

    @field_validator('confidence')
    def confidence_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['declared', 'inferred', 'width', 'model', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('declared', 'inferred', 'width', 'model', 'unknown_default_open_api')")
        return value

    @field_validator('placement')
    def placement_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['observed', 'guessed', 'unplaced', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('observed', 'guessed', 'unplaced', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SuggestedMemberView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if bit_offset (nullable) is None
        # and model_fields_set contains the field
        if self.bit_offset is None and "bit_offset" in self.model_fields_set:
            _dict['bit_offset'] = None

        # set to None if byte_offset (nullable) is None
        # and model_fields_set contains the field
        if self.byte_offset is None and "byte_offset" in self.model_fields_set:
            _dict['byte_offset'] = None

        # set to None if byte_size (nullable) is None
        # and model_fields_set contains the field
        if self.byte_size is None and "byte_size" in self.model_fields_set:
            _dict['byte_size'] = None

        # set to None if confidence (nullable) is None
        # and model_fields_set contains the field
        if self.confidence is None and "confidence" in self.model_fields_set:
            _dict['confidence'] = None

        # set to None if suggested_type (nullable) is None
        # and model_fields_set contains the field
        if self.suggested_type is None and "suggested_type" in self.model_fields_set:
            _dict['suggested_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SuggestedMemberView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bit_offset": obj.get("bit_offset"),
            "byte_offset": obj.get("byte_offset"),
            "byte_size": obj.get("byte_size"),
            "confidence": obj.get("confidence"),
            "name": obj.get("name"),
            "origin": obj.get("origin"),
            "packed": obj.get("packed"),
            "placement": obj.get("placement"),
            "suggested_type": obj.get("suggested_type"),
            "token": obj.get("token")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


