# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class Technique(BaseModel):
    """
    Technique
    """ # noqa: E501
    description: StrictStr = Field(description="How the technique appears in this binary")
    end_addr: StrictStr = Field(description="End address of the containing function, hex-encoded")
    function_addr: StrictStr = Field(description="Address of the containing function, hex-encoded")
    function_id: StrictInt = Field(description="ID of the containing function")
    function_name: StrictStr = Field(description="Name of the containing function")
    start_addr: StrictStr = Field(description="Start address of the containing function, hex-encoded")
    technique_description: StrictStr = Field(description="Full ATT&CK description of the technique")
    technique_id: StrictStr = Field(description="MITRE ATT&CK technique ID")
    technique_name: StrictStr = Field(description="MITRE ATT&CK technique name")
    technique_url: StrictStr = Field(description="Link to the technique in the ATT&CK catalogue")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["description", "end_addr", "function_addr", "function_id", "function_name", "start_addr", "technique_description", "technique_id", "technique_name", "technique_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Technique from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Technique from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "end_addr": obj.get("end_addr"),
            "function_addr": obj.get("function_addr"),
            "function_id": obj.get("function_id"),
            "function_name": obj.get("function_name"),
            "start_addr": obj.get("start_addr"),
            "technique_description": obj.get("technique_description"),
            "technique_id": obj.get("technique_id"),
            "technique_name": obj.get("technique_name"),
            "technique_url": obj.get("technique_url")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


