# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TriggerExecutionScanInputBody(BaseModel):
    """
    TriggerExecutionScanInputBody
    """ # noqa: E501
    categories: Optional[List[StrictStr]] = Field(default=None, description="Restrict findings to these categories. Omit to scan the default executes-code set.")
    direct_only: Optional[StrictBool] = Field(default=None, description="Only report functions whose own name matches a known execution API; skips the calls-into-execution pass, avoiding a bulk call-graph fetch.")
    sources: Optional[List[StrictStr]] = Field(default=None, description="Restrict findings to these sources. Omit to scan every source.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["categories", "direct_only", "sources"]

    @field_validator('categories')
    def categories_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['dynamic-resolve', 'hooking', 'injection', 'memory-exec', 'module-load', 'process-control', 'process-create', 'script-exec', 'shellcode', 'thread-create', 'unknown_default_open_api']):
                raise ValueError("each list item must be one of ('dynamic-resolve', 'hooking', 'injection', 'memory-exec', 'module-load', 'process-control', 'process-create', 'script-exec', 'shellcode', 'thread-create', 'unknown_default_open_api')")
        return value

    @field_validator('sources')
    def sources_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['boost', 'cpp', 'cpp-stdlib', 'generic', 'libc', 'qt', 'script-engine', 'windows', 'unknown_default_open_api']):
                raise ValueError("each list item must be one of ('boost', 'cpp', 'cpp-stdlib', 'generic', 'libc', 'qt', 'script-engine', 'windows', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TriggerExecutionScanInputBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if categories (nullable) is None
        # and model_fields_set contains the field
        if self.categories is None and "categories" in self.model_fields_set:
            _dict['categories'] = None

        # set to None if sources (nullable) is None
        # and model_fields_set contains the field
        if self.sources is None and "sources" in self.model_fields_set:
            _dict['sources'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TriggerExecutionScanInputBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "categories": obj.get("categories"),
            "direct_only": obj.get("direct_only"),
            "sources": obj.get("sources")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


