# coding: utf-8

"""
    RevEng.AI API

    RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from revengai.models.analyse_capabilities_body import AnalyseCapabilitiesBody
from revengai.models.report_analysis_body import ReportAnalysisBody
from typing import Optional, Set
from typing_extensions import Self

class WorkflowDayBody(BaseModel):
    """
    WorkflowDayBody
    """ # noqa: E501
    analyse_capabilities: AnalyseCapabilitiesBody = Field(description="ANALYSE_CAPABILITIES agent-task stats for the day")
    var_date: StrictStr = Field(description="Day this entry covers", alias="date")
    report_analysis: ReportAnalysisBody = Field(description="REPORT_ANALYSIS agent-task stats for the day")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["analyse_capabilities", "date", "report_analysis"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowDayBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of analyse_capabilities
        if self.analyse_capabilities:
            _dict['analyse_capabilities'] = self.analyse_capabilities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of report_analysis
        if self.report_analysis:
            _dict['report_analysis'] = self.report_analysis.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowDayBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analyse_capabilities": AnalyseCapabilitiesBody.from_dict(obj["analyse_capabilities"]) if obj.get("analyse_capabilities") is not None else None,
            "date": obj.get("date"),
            "report_analysis": ReportAnalysisBody.from_dict(obj["report_analysis"]) if obj.get("report_analysis") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


